# Generated by Django 3.1.5 on 2021-03-16 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materialimodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя материала')),
                ('cvetmateriala', models.CharField(max_length=11, verbose_name='Цвет материала')),
                ('visotavorsa', models.CharField(max_length=11, verbose_name='Высота ворса')),
                ('opisanie', models.TextField(verbose_name='Описание')),
                ('imagenews', models.ImageField(default='', upload_to='material/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('poster', models.ImageField(default='', upload_to='poster/', verbose_name='Постер')),
                ('opisanie', models.TextField(verbose_name='Описание')),
                ('datapublic', models.DateField(verbose_name='Дата публикации')),
                ('imagenews', models.ImageField(default='', upload_to='poster/', verbose_name='Изображение')),
                ('url', models.SlugField(max_length=130, unique=True)),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Obratnaya',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя покупателя')),
                ('telefon', models.CharField(max_length=12, verbose_name='Телефон')),
                ('opisanie', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Обращение',
                'verbose_name_plural': 'Обращения',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('housenumber', models.CharField(default=None, max_length=10, verbose_name='Дом №')),
                ('cenaot', models.CharField(default='', max_length=15, verbose_name='Цена от')),
                ('minopisanie', models.TextField(default=None, verbose_name='Короткое описание')),
                ('opisanie', models.TextField(verbose_name='Описание')),
                ('model_house', models.FileField(blank=True, null=True, upload_to='gltf/', verbose_name='Файл модели')),
                ('poster', models.ImageField(upload_to='poster/', verbose_name='Изображение')),
                ('treemodel', models.TextField(verbose_name='Код модели')),
                ('url', models.SlugField(max_length=130, unique=True)),
            ],
            options={
                'verbose_name': 'Продукцию',
                'verbose_name_plural': 'Продукция',
            },
        ),
        migrations.CreateModel(
            name='Svoyamodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя покупателя')),
                ('telefon', models.CharField(max_length=12, verbose_name='Телефон')),
                ('opisanie', models.TextField(verbose_name='Описание')),
                ('chertej', models.ImageField(upload_to='zakazi/', verbose_name='Чертеж модели')),
                ('shirina', models.CharField(blank=True, max_length=12, null=True, verbose_name='Ширина')),
                ('visota', models.CharField(blank=True, max_length=12, null=True, verbose_name='Высота')),
                ('glubina', models.CharField(blank=True, max_length=12, null=True, verbose_name='Глубина')),
            ],
            options={
                'verbose_name': 'Заказ по своей модели',
                'verbose_name_plural': 'Заказы по своей модели',
            },
        ),
    ]
