# Generated by Django 3.1.5 on 2021-03-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zakazmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя покупателя')),
                ('telefon', models.CharField(max_length=12, verbose_name='Телефон')),
                ('shirina', models.CharField(blank=True, max_length=12, null=True, verbose_name='Ширина')),
                ('visota', models.CharField(blank=True, max_length=12, null=True, verbose_name='Высота')),
                ('glubina', models.CharField(blank=True, max_length=12, null=True, verbose_name='Глубина')),
                ('name_house', models.CharField(blank=True, max_length=12, null=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
