# Generated by Django 3.1.5 on 2021-03-18 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_news_miniopisanie'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='typedoma',
            field=models.CharField(blank=True, default='', max_length=5, null=True, verbose_name='Тип дома'),
        ),
    ]
