# Generated by Django 3.1.5 on 2021-03-18 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_product_typedoma'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialimodel',
            name='url',
            field=models.SlugField(blank=True, default='', max_length=130, null=True),
        ),
    ]
