# Generated by Django 3.1.5 on 2021-03-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_materialimodel_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='obratnaya',
            name='temaobrash',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Ширина'),
        ),
    ]
