# Generated by Django 3.1.5 on 2021-03-19 19:27

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_obratnaya_temaobrash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='opisanie',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='obratnaya',
            name='temaobrash',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Тема'),
        ),
    ]
