# Generated by Django 3.1.5 on 2021-03-19 19:31

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210319_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='opisanie',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
