# Generated by Django 3.1.5 on 2021-03-20 11:24

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210319_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialimodel',
            name='opisanie',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
