# Generated by Django 3.1.5 on 2021-03-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210320_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zakazmodel',
            name='name_house',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название'),
        ),
    ]
